### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by Pantek59** [mrzapp/nextcloud-cookbook#9]
Hi there

For some reasons no images are shown above the recipes. When I right-click the area it says that there is an image there, but when I click on "View Image" it returns the following error message:

`The requested URL /index.php/apps/cookbook/image was not found on this server.`

Thanks the the great idea for this app and best regards!

**Comment by lmitchel** [comment]
Exactly same issue.  Version 16.0.1.  Chrome browser.

**Comment by christianlupus** [comment]
I have (I think) the same effect on firefox. I do not get any logs in the console. I get a url of `index.php/apps/cookbook/image?recipe=<recipe id>&size=full` for the image but this results in a 404 error. I do not see any errors in the logs of NC.
Cookbook 0.1.4 and NC 16.0.1 here.

**Comment by jgrete** [comment]
Same problem here - no pictures... neither FF nor Chrome

**Comment by mrzapp** [comment]
@jgrete @christianlupus @lmitchel what do you see exactly when you visit the 404'ing URL in your browser?

**Comment by christianlupus** [comment]
I get the message
```
File not found.
```
That is all I get when I visit the image URL.

If needed I could provide you access to my instance to test it.

**Comment by mrzapp** [comment]
@christianlupus sure, although before trying that, could you post the JSON file containing your recipe? (it's stored in `<your user>/Recipes` by default)

**Comment by christianlupus** [comment]
Sure, I put it [here](https://gist.github.com/christianlupus/0cc94efaa92a1c1dd7f27753fc3f94d8).

**Comment by mrzapp** [comment]
Something's up with that image URL:

![image](https://user-images.githubusercontent.com/2747428/61054306-7bbce900-a3ef-11e9-8f36-76674a9faffe.png)

It seems they escaped the URL, for what reason I can't imagine.

When I remove the extra backslashes, it works: `https://img.chefkoch-cdn.de/ck.de/rezepte/219/219330/820464-960x720-haehnchenfilet-mit-kartoffel-bohnen-salat.jpg`

**Comment by poltrian** [comment]
Change the Numbers Of servings at Chefkoch and recieps and Images are
working. But its only sometimes nessesary.

Jeppe Zapp <notifications@github.com> schrieb am Do., 11. Juli 2019, 15:22:

**Comment by jgrete** [comment]
@mrzapp When I'm using the URL from the "Image URL" I'm getting the picture:
[https://img.chefkoch-cdn.de/ck.de/rezepte/161/161614/927390-960x720-spaghetti-mit-ziegenkaese-und-kirschtomaten.jpg]
But I do not see the picture as the receipe header - only a vertical bar (see attachment)
I would love to see that working (very high WAF !)
I would also like to have a directory like possibility to structure the recepes in the left hand list - just a wish...
![2019-07-12 06_58_31-Cookbook - Nr17](https://user-images.githubusercontent.com/14105933/61103668-393cf000-a473-11e9-98d0-795276786c5a.png)

**Comment by jgrete** [comment]
@mrzapp I've made another screenshot. This time with activated, this time with activated web inspector.
Hope this is of any help for you. Hovering over the image address says: "graphic could not be loaded"
![2019-07-12 08_13_12-Cookbook - Nr17](https://user-images.githubusercontent.com/14105933/61106409-5971ac80-a47d-11e9-9945-6025ebfd0abd.png)

**Comment by mrzapp** [comment]
@jgrete I've just pulled the exact recipe you're referring to, and it works on my NextCloud instance:

![image](https://user-images.githubusercontent.com/2747428/61107545-79569f80-a480-11e9-8dfb-c5e36db2d9c6.png)

Could you visit the URL `<your nextcloud url>/index.php/apps/cookbook/image?recipe=6097753&size=full` in your browser and show me what it says?

**Comment by jgrete** [comment]
This:
![full](https://user-images.githubusercontent.com/14105933/61108653-30ecb100-a483-11e9-9ba5-b5e8548db0ed.jpg)

**Comment by jgrete** [comment]
<your nextcloud url> is not part of the URL in the web inspector above. I'm not a web developer, but shouldn't it be part of it?

**Comment by mrzapp** [comment]
@jgrete The URL in the inspector is referring to the root "/", so that implicitly means the URL to your NextCloud instance.

I can only imagine that something is wrong with your NextCloud configuration, maybe there is a content policy in effect that prevents images from being linked in this manner, or maybe it disallows embedding redirected URLs.

In any case, it doesn't seem to have anything to do with this app, so it's hard for me to help you :disappointed:

**Comment by jgrete** [comment]
Ok, I'll check that
Thx alot
Jürgen

**Comment by mrzapp** [comment]
@christianlupus [this](https://github.com/mrzapp/nextcloud-cookbook/commit/cc1e8614ce970b6b9057e1df18e24b73a86c07f4) commit should fix the problem with the backslashes

**Comment by christianlupus** [comment]
@mrzapp Thanks. This should only affect newly added recipes, right? So my existing ones might need some manual modifications on JSON level, right?

**Comment by mrzapp** [comment]
@christianlupus the app runs a sanity check every time it saves or displays a recipe, and it's in that sanity check that I implemented the URL string cleanup, so it should work on the old recipes too. If not, just edit and save them once, and you're good :+1: 

The new release, v0.1.6, is available in the store now

**Comment by christianlupus** [comment]
I am sorry but I have to say that the patch is non-functional. Do you have a current test case? Otherwise I will have update my production system to allow for temporary debugging.

**Comment by mrzapp** [comment]
@christianlupus how exactly is it non-functional? I've just tried running a clean NextCloud instance, installing the latest version works fine there. You can always remove and reinstall the app if you're having issues, your recipes are safe. Just remember to check that your settings are right when you reinstall it.

**Comment by christianlupus** [comment]
@mrzapp I installed the 0.1.6 version from the store. The image is still not visible. When changing the URL of the image in the edit page (e.g. appending a single character to the file name), this is reflected in the JSON object. However the escaping backslashes are keept in place even after the resaving of the file.

**Comment by mrzapp** [comment]
@christianlupus I've copied the exact JSON content of the example you gave me [here](https://gist.githubusercontent.com/christianlupus/0cc94efaa92a1c1dd7f27753fc3f94d8/raw/30715291128f276730dfa0139a4b0c2729b03cc8/H%25C3%25A4hnchenfilet%2520mit%2520Kartoffel-Bohnen-Salat.json) and saved it as a JSON file. 

This is how that file reads after rescanning the library:

![image](https://user-images.githubusercontent.com/2747428/61116194-3f8f9400-a494-11e9-8248-fa179c7b62cc.png)

Maybe try that?

![image](https://user-images.githubusercontent.com/2747428/61116350-92694b80-a494-11e9-865a-10ef73a3b49c.png)

**Comment by christianlupus** [comment]
This is strange. I tried rescanning the library without success. In the meantime I have the feeling that the Symfony framework used deep inside does nasty things.

I try to generate php debug traces from various calls to URLs but these already generated  are huge and I did not yet made my way through them.

**Comment by mrzapp** [comment]
@christianlupus dang! You may be right about that. I've tried doing the same, but there are no error log entries when I use the app.

I'd recommend spinning up a fresh NextCloud instance and try to reproduce the problem. The one you're running might be haunted :sweat_smile: 

Or, I might be doing things terribly wrong, carefully making sure to only affect everyone else using this app.

**Comment by christianlupus** [comment]
@mrzapp  I just found some hint: My nextcloud instance is running in the path `/nextcloud` of my server, not in the root directory. This causes the images to be invisible as the URL if the image misses exactly this small part of the path. When I add it manually (for debugging purposes), I can see the image.
So the question is: Why is the relative path of the instance dropped in favor of the root folder of the web server? Is this in your code (I am sorry, I did not read and understand every tiny bit of it) or somewhere in the core of NC?

**Comment by mrzapp** [comment]
@christianlupus That is very likely the cause, I have never tested this with NC running in anything but the root. I'll look into it!

**Comment by mrzapp** [comment]
@christianlupus a fix has been published using the `IURLGenerator`. That seems to have fixed it for me. @jgrete does this solve your issue too?

**Comment by lmitchel** [comment]
Thank you - that solved it for me too!  No need to even reindex, just started working.

**Comment by mrzapp** [comment]
@lmitchel glad to hear it 😊

**Comment by jgrete** [comment]
Wow! I can see clearly now, the rain is gone...
Whatever you've done - I can see all images now. Perfect!
Thanks alot
Jürgen

**Comment by christianlupus** [comment]
@mrzapp I just tested it and it works like a charm. Thanks :+1:
